### ISSUE TITLE
Ajouter un bouton pour fermer la popup finale

### ISSUE THREAD

**Issue by marcbertholet** [marcbertholet/map#7]
Pour permettre à une popup d'être fermée en cliquant sur une petite croix en haut à droite de la fenêtre, il faut ajouter une structure HTML pour la croix, et un peu de CSS et JavaScript pour gérer son apparence et son comportement.

Voici un exemple de mise en œuvre :

### HTML
Ajoutez une croix dans votre popup :
```html
<div class="popup">
  <div class="popup-header">
    <span class="close-btn">&times;</span>
  </div>
  <div class="popup-content">
    <p>Contenu de la popup</p>
  </div>
</div>
```

### CSS
Ajoutez du style pour positionner la croix et styliser votre popup :
```css
.popup {
  position: fixed;
  top: 50%;
  left: 50%;
  transform: translate(-50%, -50%);
  padding: 20px;
  background: white;
  box-shadow: 0 4px 8px rgba(0, 0, 0, 0.2);
  z-index: 1000;
}

.popup-header {
  display: flex;
  justify-content: flex-end;
}

.close-btn {
  font-size: 24px;
  font-weight: bold;
  cursor: pointer;
}
```

### JavaScript
Ajoutez le comportement pour fermer la popup lorsque la croix est cliquée :
```javascript
document.querySelector('.close-btn').addEventListener('click', function () {
  document.querySelector('.popup').style.display = 'none';
});
```

### Intégration dans votre fichier `index.html`
Je peux récupérer le contenu actuel du fichier `index.html` pour y ajouter ce code si vous le souhaitez. Dois-je récupérer le fichier pour y intégrer cette modification ?
